### ISSUE TITLE
Setup database backup

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/caltechdata#3]

**Comment by rsdoiel** [comment]
I'll work on this after we confirm Shibboleth is correct.

**Comment by rsdoiel** [comment]
Here's a decription from stackexchange "How to backup a dockerized Postgres"

https://stackoverflow.com/questions/24718706/backup-restore-a-dockerized-postgresql-database

**Comment by rsdoiel** [comment]
This is solved but needs to be setup in a nightly cronjob.  See https://caltechlibrary.atlassian.net/wiki/spaces/IRM/pages/2663383053/Invenio+RDM+system+administration on how it works and the /home/ubuntu/backup-postgres.bash script for details.

**Comment by rsdoiel** [comment]
The correct URLs for my Invenio-RDM documentation are 

- https://caltechlibrary.atlassian.net/wiki/spaces/DLD/pages/2668593163/Invenio-RDM+System+Admin
- https://caltechlibrary.atlassian.net/wiki/spaces/DLD/pages/2669051934/Converting+Invenio-RDM+9.1+to+use+Shibboleth+for+SSO

I will have to recreate my documentation on backing up PostgreSQL in a dockerized setting.

**Comment by rsdoiel** [comment]
I added invenio-sql-backups.bash. It is setup on as a nightly cronjob. The postgres DB_USERNAME is set in the "postgres_env.cfg" file.  Any additional information can be included there if we need. I've added an entry to .gitignore to ignore backing up that file in the future should we decide to also include sensitive info like a db password. I added an example file to show how it works.

**Comment by rsdoiel** [comment]
I've tried to restore from the dump on my local dev box. The restore has errors. This might be due to version differences. It looks like Invenio is using Postgres 12, the current stable is Postgres 14.5 and Postgres 15 as the new stable is expected to arrive in September. The specific error is regarding missing template1 which is included in the "DROP DATABASE" statements.  This seems wrong to me. I've tried both `psql -f DB_DUMP_FILENAME` and `pg_restore -f DB_DUMP_FILENAME`. The first produces the error, the second never completes and both don't create the database inspite of the database CREATE statements.

**Comment by rsdoiel** [comment]
Switch from using `pg_dumpall` to `pg_dump caltechdata` in script.  The values DB_NAME and DB_USERNAME must be in the environment when `invenio-sql-backup.bash` is running. These can be configured in the `postgres_env.cfg` file.

Restoring a database is just a matter of doing the follow (replace "<DUMP_FILENAME>" with the name of the file to restore the database without).

```
psql -c 'DROP DATABASE caltechdata'
psql -c 'CREATE DATABASE caltechdata'
psql caltechdata -f <DUMP_FILENAME>
```
